name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set working directory a la carpeta del proyecto
      - name: Set working directory
        run: cd lab3_codespaces_ruff
        shell: bash

      # 3. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 4. Instala dependencias
      - name: Install dependencies
        working-directory: lab3_codespaces_ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Linters
      - name: Run ruff
        working-directory: lab3_codespaces_ruff
        run: ruff check src test

      - name: Run mypy
        working-directory: lab3_codespaces_ruff
        run: mypy src test

      # 6. Tests
      - name: Run pytest
        working-directory: lab3_codespaces_ruff
        run: |
          PYTHONPATH=$(pwd) pytest
