# -*- coding: utf-8 -*-
"""main_modulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmwyh8hIh22caCVRq7z_tiwTH9FEX5kP
"""

# main_modulo.py
from datetime import datetime
import utilidades_fecha as uf

# Ejemplo de uso
hoy = datetime.now()
otra_fecha = datetime(2025, 1, 1)

print("Hoy formateado:", uf.formatear_fecha(hoy, "%d/%m/%Y"))
print("Diferencia en días:", uf.diferencia_dias(hoy, otra_fecha))
print("Validar fecha correcta:", uf.validar_fecha("2025-08-14"))
print("Validar fecha incorrecta:", uf.validar_fecha("2025/14/08"))
print("Sumar días:", uf.formatear_fecha(uf.sumar_dias(hoy, 10)))


if not uf.validar_fecha("2025-13-01"):
    print("Error: Fecha no válida detectada correctamente.")