# -*- coding: utf-8 -*-
"""utilidades_fecha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCA5qiFsL6JDJg3iOGViy2aHHXqwVZxw
"""

from datetime import datetime, timedelta

def formatear_fecha(fecha: datetime, formato: str = "%Y-%m-%d") -> str:
    """Devuelve la fecha formateada según el formato indicado."""
    return fecha.strftime(formato)

def diferencia_dias(fecha1: datetime, fecha2: datetime) -> int:
    """Calcula la diferencia en días entre dos fechas."""
    return abs((fecha2 - fecha1).days)

def validar_fecha(cadena_fecha: str, formato: str = "%Y-%m-%d") -> bool:
    """Valida si la cadena corresponde a una fecha con el formato dado."""
    try:
        datetime.strptime(cadena_fecha, formato)
        return True
    except ValueError:
        return False

def sumar_dias(fecha: datetime, dias: int) -> datetime:
    """Devuelve una nueva fecha sumando o restando días."""
    return fecha + timedelta(days=dias)