# -*- coding: utf-8 -*-
"""main_paquete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9zYXDF30VmZpwKatkPD3LiDQL43zxbj
"""

from datetime import datetime
from mi_paquete_fechas import formatear, dias_entre, fecha_mas_dias

hoy = datetime.now()
futuro = datetime(2025, 12, 31)

print("Hoy:", formatear(hoy, "%d/%m/%Y"))
print("Días hasta fin de año:", dias_entre(hoy, futuro))
print("Fecha + 15 días:", fecha_mas_dias(hoy, 15))