# -*- coding: utf-8 -*-
"""ejercicioC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4OYiHbK6EXTUHqOD_C3Kb0EeuGPAzLb
"""

from typing import Union, Optional

def sumar(a: int, b: int) -> int:
    return a + b

def procesar(valor: Optional[Union[int, str]]) -> None:
    print(valor)

print("Suma:", sumar(3, 4))
procesar(10)
procesar("Hola")
procesar(None)


procesar(3.14)