# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CzWFr3MbyuMthKF26ILhP0xlLRQZ0WFh
"""

from .formateo import formatear
from .calculos import dias_entre, fecha_mas_dias

__all__ = ["formatear", "dias_entre", "fecha_mas_dias"]