# -*- coding: utf-8 -*-
"""calculos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0AVNh8Ryb9lIAtFROkLHJjYdZvpUdAk
"""

from datetime import datetime
from .formateo import formatear

def dias_entre(fecha1: datetime, fecha2: datetime) -> int:
    return abs((fecha2 - fecha1).days)

def fecha_mas_dias(fecha: datetime, dias: int) -> str:
    """Usa formatear() desde formateo.py para devolver la fecha como texto"""
    from datetime import timedelta
    nueva_fecha = fecha + timedelta(days=dias)
    return formatear(nueva_fecha)