# -*- coding: utf-8 -*-
"""formateo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvGcb4sY3OZz-3VXFAiW3XAq1-lzwsfe
"""

from datetime import datetime

def formatear(fecha: datetime, formato: str = "%Y-%m-%d") -> str:
    return fecha.strftime(formato)