name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Instala dependencias
      - name: Install dependencies
        working-directory: lab3_codespaces_ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Linters
      - name: Run ruff
        working-directory: lab3_codespaces_ruff
        run: ruff check src

      - name: Run mypy
        working-directory: lab3_codespaces_ruff
        run: mypy src

      # 5. Tests
      - name: Run pytest
        working-directory: lab3_codespaces_ruff
        run: |
          PYTHONPATH=$(pwd) pytest
