name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequea el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Instala dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest

      # 4. Ejecuta linters
      - name: Run ruff
        run: ruff check src test

      - name: Run mypy
        run: mypy src test

      # 5. Ejecuta tests
      - name: Run pytest
        run: pytest
